services:

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - appnetwork

  app:
    build: 
      context: .
    expose: 
      - ${PORT}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    networks:
      - appnetwork
    env_file: .env

networks:              
  appnetwork:
    driver: bridge